tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "outline-variant": "#3b494b",
                        "on-secondary": "#520072",
                        "on-secondary-fixed-variant": "#74009f",
                        "on-tertiary-fixed": "#1a1b1e",
                        "inverse-surface": "#e5e2e3",
                        "surface-container": "#201f20",
                        "inverse-primary": "#006970",
                        "tertiary": "#f7f5f9",
                        "error-container": "#93000a",
                        "on-primary-container": "#006970",
                        "on-primary": "#00363a",
                        "tertiary-fixed-dim": "#c7c6ca",
                        "inverse-on-surface": "#313031",
                        "surface-container-lowest": "#0e0e0f",
                        "on-surface": "#e5e2e3",
                        "on-primary-fixed-variant": "#004f54",
                        "on-error-container": "#ffdad6",
                        "background": "#131314",
                        "on-secondary-fixed": "#320047",
                        "on-error": "#690005",
                        "surface-bright": "#39393a",
                        "primary": "#dbfcff",
                        "on-tertiary-container": "#5e5e62",
                        "primary-fixed-dim": "#00dbe9",
                        "on-tertiary-fixed-variant": "#46474a",
                        "surface-container-high": "#2a2a2b",
                        "secondary-container": "#b600f8",
                        "on-surface-variant": "#b9cacb",
                        "on-tertiary": "#2f3033",
                        "primary-fixed": "#7df4ff",
                        "on-secondary-container": "#fff6fc",
                        "surface-container-low": "#1c1b1c",
                        "outline": "#849495",
                        "secondary-fixed-dim": "#ebb2ff",
                        "surface-dim": "#131314",
                        "surface-container-highest": "#353436",
                        "primary-container": "#00f0ff",
                        "surface": "#131314",
                        "surface-tint": "#00dbe9",
                        "tertiary-fixed": "#e3e2e6",
                        "tertiary-container": "#dad9dd",
                        "secondary-fixed": "#f8d8ff",
                        "on-primary-fixed": "#002022",
                        "secondary": "#ebb2ff",
                        "on-background": "#e5e2e3",
                        "error": "#ffb4ab",
                        "surface-variant": "#353436"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "base": "8px",
                        "gutter": "24px",
                        "container-max": "1200px",
                        "margin-desktop": "48px",
                        "margin-mobile": "16px"
                    },
                    "fontFamily": {
                        "body-lg": ["Geist", "Inter"],
                        "body-md": ["Geist", "Inter"],
                        "display-lg": ["Space Grotesk"],
                        "label-mono": ["JetBrains Mono"],
                        "display-lg-mobile": ["Space Grotesk"],
                        "label-caps": ["JetBrains Mono"],
                        "headline-sm": ["Space Grotesk"],
                        "headline-md": ["Space Grotesk"]
                    },
                    "fontSize": {
                        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                        "label-mono": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
                        "display-lg-mobile": ["36px", {"lineHeight": "1.1", "fontWeight": "700"}],
                        "label-caps": ["12px", {"lineHeight": "1", "fontWeight": "700"}],
                        "headline-sm": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
                        "headline-md": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}]
                    }
                },
            },
        }